FROM python:alpine3.9

MAINTAINER  Jerven Clark Chua <jervenclark@gmail.com>

COPY ./files/repositories /etc/apk/repositories

RUN apk update && apk add python3 fabric@testing && \
  python3 -m ensurepip && rm -r /usr/lib/python*/ensurepip && \
  if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
  if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi

RUN mkdir /home/app

WORKDIR /home/app
